### ISSUE TITLE
remote the DB

### ISSUE THREAD

**Issue by ghost** [matei-tm/f-orm-m8-sqlite#101]
It would be useful if the SQLite DB can be server side.
The developer would still use annotations in their FLutter code just as the developer does snow.

I presume at Build time, you creating SQL Tables with the right Schema, PF; PF, etc. ?

SO then people can run on Desktop using this:
https://github.com/nealwon/go-flutter-plugin-sqlite

Which has an ORM also.
https://github.com/go-xorm/xorm

Btw you can also compile this golang flutter plugin to run on mobiles using gomobile.
https://www.arputer.com/using-go-library-in-flutter

So in the end, the SQL is being generated into a backend SQLite.

**Comment by matei-tm** [comment]
Good idea. The package is not limited to Flutter. It's written in Dart and and formally is Flutter independent. In conclusion, it can be implemented in many ways: compiled as JavaScript, stand-alone in Dart VM, compiled ahead-of-time in machine code. Currently we have a `sqflite` dependency that pin us to Flutter but, in the future versions, we plan to split the project into a generator project and several database providers.

**Comment by matei-tm** [comment]
I will close this issue as it is not the case for the current implementation. The idea to generate server side code is great and it will be possible when we decouple the generator from the sqflite. This is a request for Milestone  v0.0.9 and is described on #106
